GET http://localhost:4000/api/expenses

###
PUT http://localhost:4000/api/expenses/edit-expense/10
Content-Type: application/json

{
    "amount": 25,
    "description": "description",
    "category": "Electricity"
}